# Generated by Django 5.0.6 on 2024-06-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_mytable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
